  default: &default
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    timeout: 5000

  development:
    <<: *default
    host: localhost
    username: postgres
    password: '12345'
    database: admin_app

  test:
    <<: *default
    host: localhost
    username: postgres
    password: '12345'
    database: admin_app

  production:
    <<: *default
    database: db/production.sqlite3
